### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by bpassos-zz** [bpassos/salaris#5]

**Comment by weslleyaraujo** [comment]
Hey @bpassos,

Just added the `npm run build-css`  as one of the npm package tasks 😆

I dont know if there is a need to use some task runner such as gulp/grunt or if we can keep going with those simple scripts through npm.. maybe in a future we can change for something like that.

Now, if you run the `npm run build` it will generate both css and js files 💪

(also added the dependency of [`cssmin`](https://www.npmjs.com/package/cssmin) globally)
